version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: academic_postgres
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: academic_helper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: academic_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://student:secure_password@postgres:5432/academic_helper
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./backend:/app  
      - shared_uploads:/app/uploads 
    depends_on:
      - postgres
    networks:
      - app_network

  n8n:
    image: n8nio/n8n:latest
    container_name: academic_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Africa/Addis_Ababa
      - N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES=false
    volumes:
      - n8n_data:/home/node/.n8n
      - shared_uploads:/home/node/.n8n-files
    networks:
      - app_network

volumes:
  postgres_data:
  n8n_data:
  shared_uploads:

networks:
  app_network:
    driver: bridge